USE "master";
GO

CREATE DATABASE "Repartos"
CONTAINMENT = NONE ON PRIMARY 
(
	NAME = N'Repartos',
	FILENAME = N'D:\Users\Jamesit0\Documents\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\repartos.mdf',
	SIZE = 8192KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 65536KB
)
LOG ON 
(
	NAME = N'Repartos_log',
	FILENAME = N'D:\Users\Jamesit0\Documents\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\Log\repartos.ldf',
	SIZE = 8192KB,
	MAXSIZE = 2048GB,
	FILEGROWTH = 65536KB
)
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (FULLTEXTSERVICEPROPERTY('IsFullTextInstalled') = 1)
	BEGIN
		EXECUTE "Repartos"."dbo"."sp_fulltext_database"
			@action = 'enable';
	END;
GO

ALTER DATABASE "Repartos" SET ANSI_NULL_DEFAULT OFF;
GO

ALTER DATABASE "Repartos" SET ANSI_NULLS OFF;
GO

ALTER DATABASE "Repartos" SET ANSI_PADDING OFF;
GO

ALTER DATABASE "Repartos" SET ANSI_WARNINGS OFF;
GO

ALTER DATABASE "Repartos" SET ARITHABORT OFF;
GO

ALTER DATABASE "Repartos" SET AUTO_CLOSE OFF;
GO

ALTER DATABASE "Repartos" SET AUTO_SHRINK OFF;
GO

ALTER DATABASE "Repartos" SET AUTO_UPDATE_STATISTICS ON;
GO

ALTER DATABASE "Repartos" SET CURSOR_CLOSE_ON_COMMIT OFF;
GO

ALTER DATABASE "Repartos" SET CURSOR_DEFAULT  GLOBAL;
GO

ALTER DATABASE "Repartos" SET CONCAT_NULL_YIELDS_NULL OFF;
GO

ALTER DATABASE "Repartos" SET NUMERIC_ROUNDABORT OFF;
GO

ALTER DATABASE "Repartos" SET QUOTED_IDENTIFIER OFF;
GO

ALTER DATABASE "Repartos" SET RECURSIVE_TRIGGERS OFF;
GO

ALTER DATABASE "Repartos" SET DISABLE_BROKER;
GO

ALTER DATABASE "Repartos" SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
GO

ALTER DATABASE "Repartos" SET DATE_CORRELATION_OPTIMIZATION OFF;
GO

ALTER DATABASE "Repartos" SET TRUSTWORTHY OFF;
GO

ALTER DATABASE "Repartos" SET ALLOW_SNAPSHOT_ISOLATION OFF;
GO

ALTER DATABASE "Repartos" SET PARAMETERIZATION SIMPLE;
GO

ALTER DATABASE "Repartos" SET READ_COMMITTED_SNAPSHOT OFF;
GO

ALTER DATABASE "Repartos" SET HONOR_BROKER_PRIORITY OFF;
GO

ALTER DATABASE "Repartos" SET RECOVERY FULL;
GO

ALTER DATABASE "Repartos" SET  MULTI_USER;
GO

ALTER DATABASE "Repartos" SET PAGE_VERIFY CHECKSUM;
GO

ALTER DATABASE "Repartos" SET DB_CHAINING OFF;
GO

ALTER DATABASE "Repartos" SET FILESTREAM
(
	NON_TRANSACTED_ACCESS = OFF
);
GO

ALTER DATABASE "Repartos" SET TARGET_RECOVERY_TIME = 60 SECONDS;
GO

ALTER DATABASE "Repartos" SET DELAYED_DURABILITY = DISABLED;
GO

ALTER DATABASE "Repartos" SET QUERY_STORE = OFF
GO

ALTER DATABASE "Repartos" SET  READ_WRITE;
GO